# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# Imports and service definitions will be generated from balance.proto.
# Placeholder: run `make proto` to regenerate

class BalanceAPIServicer:  # placeholder for type reference in server
    pass

